name: 'Single Node Kubernetes Cluster'
description: 'Installs a Minikube powered single node Kubernetes cluster in your Github Actions workflow.'
branding:
  icon: 'download-cloud'
  color: 'blue'
inputs:
  minikube-version:
    description: 'Minikube version to install'
    required: false
    default: '1.6.2'
  k8s-version:
    description: 'Kubernetes version to install'
    required: false
    default: '1.17.0'
outputs:
  launcher:
    description: 'Command to execute to launch minikube'
runs:
  using: 'node12'
  main: 'src/index.js'